# Generated by Django 3.0.5 on 2020-06-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='kierownik',
            field=models.BooleanField(default=False),
        ),
    ]
